### ISSUE TITLE
Module naming

### ISSUE THREAD

**Issue by lpil** [rjdellecese/gleam_jsone#5]
Hello! I was trying this library and I ended up with some code that looked like this:

```rust
import gleam/jsone/encode
import gleam/jsone/encode
```
```rust
let json = encode.encode_json(value)
let term = decode.decode_json(string)
```

Looking at this code I wondered if it would be clearer if the module name was adjusted and there was one module for the public API:

```rust
import gleam/jsone
```
```rust
let json = jsone.encode(value)
let term = jsone.decode(string)
```

Just an idle thought. :)

This isn't really an "issue", so I'll close this as it's not a task

**Comment by rjdellecese** [comment]
Thank you for the feedback, @lpil!

I hear you, and had also wondered the same thing. I agree that the usage in your example feels a bit awkward.

The main reason I chose this module naming structure was that I thought the encoding functions would feel better to use this way. The usage I envisioned was like so:

```rust
import gleam/jsone/encode.{encode_json, JsonValue}

pub fn encode_person(name: String, age: Int) -> JsonValue {
  encode.object([
    tuple("name", encode.string(name)),
    tuple("age", encode.int(age))
  ])
  |> encode_json
}
```

So I guess that would be in contrast to something like this:

```rust
import gleam/jsone.{JsonValue}

pub fn encode_person(name: String, age: Int) -> JsonValue {
  jsone.encode_object([
    tuple("name", jsone.encode_string(name)),
    tuple("age", jsone.encode_int(age))
  ])
  |> jsone.encode
}
```

I still think I might like the former a little better... if you wanted to make it really clear what kind of data you were encoding, you could always alias the import, e.g.

```rust
import gleam/jsone/encode.{encode_json, JsonValue} as jsone_encode

pub fn encode_person(name: String, age: Int) -> JsonValue {
  jsone_encode.object([
    tuple("name", jsone_encode.string(name)),
    tuple("age", jsone_encode.int(age))
  ])
  |> encode_json
}
```

But I'll keep thinking about it!

Thank you again for the input! :)

**Comment by lpil** [comment]
Given type specific functions are not required for decoding I think the `encode_` prefix would be redundant- the second example you give could be this:

```rust
import gleam/jsone.{JsonValue}

pub fn encode_person(name: String, age: Int) -> JsonValue {
  jsone.object([
    tuple("name", jsone.string(name)),
    tuple("age", jsone.int(age))
  ])
  |> jsone.encode
}
```

This is the most concise, has unambiguous module names without renaming, and requires only a single module import.

**Comment by rjdellecese** [comment]
I'm persuaded—I like that better. Reopening to track as a task.
